name: .NET

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./XHealthWeb/XHealthWeb.csproj

    - name: Install npm dependencies
      run: |
        cd XHealthWeb/clientapp
        npm install || exit 1
        
    - name: Build
      run: dotnet build ./XHealthWeb/XHealthWeb.csproj --no-restore || exit 0
       if grep -q 'webpack compiled with [1-9][0-9]* warning'; then
          echo "Build completed with warnings"
        fi

    - name: Test
      run: dotnet test ./XHealthWeb/XHealthWeb.csproj --no-build --verbosity normal
