name: .NET

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./XHealthWeb/XHealthWeb.csproj

    - name: Install npm dependencies
      run: |
        if [ -f ./XHealthWeb/clientapp/package.json ]; then
          cd XHealthWeb/clientapp
          npm install
        else
          echo "package.json not found in the specified directory."
          exit 1
        fi

    - name: Build
      run: dotnet build ./XHealthWeb/XHealthWeb.csproj --no-restore

    - name: Test
      run: dotnet test ./XHealthWeb/XHealthWeb.csproj --no-build --verbosity normal
